services:
  rabbitmq:
    image: rabbitmq:4.2.4
    ports:
      - "${RABBITMQ_PORT_UI}:15672"
      - "${RABBITMQ_PORT_AMQP}:5672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 3s
    env_file: .env

  postgres:
    image: postgres:18.3-alpine
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    env_file: .env
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 3s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "${FRONTEND_EXTERNAL_PORT}:80"
    env_file: .env

  backend:
    build:
      context: ./backend
      dockerfile: .docker/Dockerfile
    container_name: backend
    ports:
      - "8080:8080"
    env_file: .env
    environment:
      - GIN_MODE=release
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres:
        condition: service_healthy

  evaluator:
    build:
      context: ./evaluator
      dockerfile: Dockerfile
    container_name: evaluator
    env_file: .env
    depends_on:
      rabbitmq:
        condition: service_healthy

volumes:
  rabbitmq_data:
    driver: local
  postgres_data:
    driver: local
